import { readdirSync, readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { join, relative } from "node:path";
const WWW = join(import.meta.dirname, "..", "www");
const OUT = join(import.meta.dirname, "..", "src", "files.generated.ts");
function walk(dir) {
    const entries = readdirSync(dir, { withFileTypes: true });
    const files = [];
    for (const e of entries) {
        const full = join(dir, e.name);
        if (e.isDirectory()) {
            files.push(...walk(full));
        }
        else {
            files.push(full);
        }
    }
    return files;
}
mkdirSync(join(import.meta.dirname, "..", "src"), { recursive: true });
const files = walk(WWW);
const entries = [];
for (const f of files) {
    const rel = `/${relative(WWW, f)}`;
    const content = readFileSync(f, "utf-8");
    const escaped = content
        .replace(/\\/g, "\\\\")
        .replace(/`/g, "\\`")
        .replace(/\$/g, "\\$");
    entries.push(`\t${JSON.stringify(rel)}: \`${escaped}\``);
}
const out = `// AUTO-GENERATED by scripts/build-files.ts — do not edit manually
// Source: www/ directory (${files.length} files)

export const FILES: Record<string, string> = {
${entries.join(",\n")}
};
`;
writeFileSync(OUT, out);
console.log(`Generated ${OUT} (${files.length} files, ${(Buffer.byteLength(out) / 1024 / 1024).toFixed(1)} MB)`);
//# sourceMappingURL=build-files.js.map