import { readdirSync, readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { join, relative } from "node:path";

const WWW = join(import.meta.dirname, "..", "www");
const OUT = join(import.meta.dirname, "..", "src", "files.generated.ts");

function walk(dir: string): string[] {
	const entries = readdirSync(dir, { withFileTypes: true });
	const files: string[] = [];
	for (const e of entries) {
		const full = join(dir, e.name);
		if (e.isDirectory()) {
			files.push(...walk(full));
		} else {
			files.push(full);
		}
	}
	return files;
}

function toIdentifier(rel: string): string {
	const clean = rel.replace(/^\//, "");
	const ext = clean.includes(".") ? clean.split(".").pop()! : "";
	const base = clean.replace(/\.[^.]+$/, "");
	const withExt = ext ? `${base}_${ext}` : base;
	const id = withExt.replace(/[^a-zA-Z0-9]/g, "_");
	return id.startsWith("_") ? id : `_${id}`;
}

mkdirSync(join(import.meta.dirname, "..", "src"), { recursive: true });

const files = walk(WWW);
const entries: string[] = [];
const mockEntries: string[] = [];
const pathLiterals: string[] = [];

for (const f of files) {
	const rel = `/${relative(WWW, f)}`;
	const content = readFileSync(f, "utf-8");
	const escaped = content
		.replace(/\\/g, "\\\\")
		.replace(/`/g, "\\`")
		.replace(/\$/g, "\\$");
	entries.push(`\t${JSON.stringify(rel)}: \`${escaped}\``);

	const key = toIdentifier(rel);
	mockEntries.push(`\t/** ${rel} */\n\t${key}: ${JSON.stringify(rel)}`);
	pathLiterals.push(JSON.stringify(rel));
}

const pathType = pathLiterals.join(" | ");

const out = `// AUTO-GENERATED by scripts/build-files.ts — do not edit manually
// Source: www/ directory (${files.length} files)

export const FILES: Record<string, string> = {
${entries.join(",\n")}
};

/**
 * Union of all valid www/ file paths.
 * Use with {@link loadWww} or {@link wwwExists} for type-safe access.
 */
export type MockupPath = ${pathType};

/**
 * Named constants for all www/ file paths.
 *
 * @example
 * \`\`\`ts
 * import { loadWww, MockupPaths } from "wordpress-honeypot";
 *
 * const content = loadWww(MockupPaths._wp_login_php, config);
 * \`\`\`
 */
export const MockupPaths = {
${mockEntries.join(",\n")}
} as const;
`;

writeFileSync(OUT, out);
console.log(
	`Generated ${OUT} (${files.length} files, ${(Buffer.byteLength(out) / 1024 / 1024).toFixed(1)} MB)`,
);
