/** Generator function that produces honeypot content for a given site configuration. */
export type Gen = (config: SiteConfig) => string;

/** Pattern matcher: exact string, regex, or predicate function. */
export type Matcher = string | RegExp | ((endpoint: string) => boolean);

/** Factory that creates a Gen from an endpoint string. */
export type GenFactory = (endpoint: string) => Gen;

/** A route rule pairing a matcher with a generator factory. */
export interface RouteRule {
	/** Pattern to match against the request path. */
	match: Matcher;
	/** Factory that produces the generator for matched endpoints. */
	gen: GenFactory;
}

/**
 * Site configuration for the honeypot.
 *
 * All fields are optional except `domain`, which can also be
 * auto-detected from request headers (`Host`, `X-Forwarded-Host`).
 *
 * @example
 * ```ts
 * const config: SiteConfig = {
 *   domain: "example.com",
 *   siteName: "my-blog",
 *   dbName: "wp_production",
 *   dbUser: "wp_admin",
 *   dbPassword: "s3cur3P@ss",
 * };
 * ```
 */
export interface SiteConfig {
	/**
	 * Site domain (e.g. `"example.com"`).
	 * Used in URLs, Apache configs, backups, logs, etc.
	 * Auto-detected from `Host` header if omitted.
	 */
	domain: string;

	/**
	 * Site name (e.g. `"my-blog"`).
	 * Used in file paths, database names, comments.
	 * Auto-derived from domain if omitted (e.g. `"example"` from `"example.com"`).
	 */
	siteName?: string;

	/**
	 * MySQL database name.
	 * @default "wordpress"
	 */
	dbName?: string;

	/**
	 * MySQL database user.
	 * @default "wp_admin"
	 */
	dbUser?: string;

	/**
	 * MySQL password. Appears in `.my.cnf`, `backup.sh`, `wp-config.php`, etc.
	 * @default "change_me"
	 */
	dbPassword?: string;

	/**
	 * Admin email address. Used in Apache config, `.env` files, SQL dumps.
	 * @default "admin@{domain}"
	 */
	adminEmail?: string;

	/**
	 * PHP version string for `X-Powered-By` header.
	 * @default "7.4.33"
	 */
	phpVersion?: string;

	/**
	 * Server software string for `Server` header.
	 * @default "Apache/2.4.51 (Debian)"
	 */
	serverSoftware?: string;

	/**
	 * Backend server hostname for `X-Backend-Server` header.
	 * @default "web-01"
	 */
	serverName?: string;

	/**
	 * VPS IP address. Appears in `notes.md`, `.bash_history`.
	 * @default "0.0.0.0"
	 */
	vpsIp?: string;

	/**
	 * SSH port. Appears in `notes.md`, `.bash_history`, `.env.backup`.
	 * @default 22
	 */
	sshPort?: number;

	/**
	 * Webroot path on the server.
	 * @default "/var/www/{domain}/public_html"
	 */
	webroot?: string;

	/**
	 * WordPress theme name. Appears in `debug.log`, SQL dumps.
	 * @default "theme"
	 */
	themeName?: string;
}

/**
 * HTTP response generated by the honeypot.
 */
export interface HoneypotResponse {
	/** HTTP status code (always 200). */
	status: number;
	/** Response headers including realistic PHP/Server headers. */
	headers: Record<string, string>;
	/** Response body (HTML, plain text, JSON, or PHP source). */
	body: string;
}

/**
 * Framework adapter function type.
 * Returns a middleware/handler for the given framework.
 */
export type FrameworkAdapter = (
	config?: Partial<SiteConfig>,
	options?: { emitter?: import("./emitter.js").HoneypotEmitter },
) => (req: any, res: any, next?: any) => void;
